<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>KinopoiskWhite</AssemblyName>
    <RootNamespace>KinopoiskWhite</RootNamespace>
    <Version>1.0.2</Version>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    
    <DebugType>portable</DebugType>
  </PropertyGroup>

   <ItemGroup>
    <PackageReference Include="Jellyfin.Data" Version="12.1.0" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" />
    <PackageReference Include="Jellyfin.Common" Version="12.1.0" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />

    <EmbeddedResource Include="Api\Queries\*.gql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>

    <EmbeddedResource Include="Common\config.html">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
